default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fanfiction_viewer_development

test:
  <<: *default
  database: fanfiction_viewer_test

production:
  <<: *default
  database: fanfiction_viewer_production
  username: fanfiction_viewer
  password: <%= ENV['FANFICTION_VIEWER_DATABASE_PASSWORD'] %>
